BASE_URL = 'https://apinew.iecp.ru/api/external/v2'
URL_METHOD_REQUEST_VIEW = BASE_URL + '/request/view'
URL_METHOD_REQUEST_RESULT = BASE_URL + '/request/result'
URL_METHOD_REQUEST_LIST = BASE_URL + '/request/list'
URL_METHOD_REQUEST_CREATE = BASE_URL + '/request/create'
URL_METHOD_REQUEST_CHANGE = BASE_URL + '/request/change'
